application: the-seagull-effect
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: the-seagull-effect.application

libraries:
- name: PIL
  version: "1.1.7"
- name: webapp2
  version: latest
- name: numpy
  version: latest
- name: django
  version: latest
